# Use postgres/example user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: trabalho-web
      MONGO_INITDB_ROOT_PASSWORD: trabalho-web
    ports:
      - "27017:27017"